# Generated by Django 3.2.5 on 2021-09-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whether_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whether',
            name='city',
        ),
    ]
